### ISSUE TITLE
Error with tablets and smartphones

### ISSUE THREAD

**Issue by bukosabino** [jaysalvat/buzz#101]
Hi, I get this error in tablets and smartphones with buzz:
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture. 

However, I don't have errors in this demo: http://buzz.jaysalvat.com/demo/ 

:S

**Comment by jaysalvat** [comment]
Hello,

Not a Buzz bug but a HTMLMediaElement limitation of mobile. The error message is pretty self explanatory "HTMLMediaElement': API can only be initiated by a user gesture." :)

It is written in Buzz doc.
http://buzz.jaysalvat.com/documentation/sound/
"* NOTE: In order to save bandwidth, mobile devices don't load/play sounds without user intervention (no autoplay). iPhone and iPad can only play one sound at a time and don't allow to change the volume dynamically. iPad has some issues with multiple sounds on the same page."
